# ML Project Assignment

Q.1) Create a folder in which you want to create the project, after that use the git init and the necessary
co\\ands to create the specific @it repository

Navigate to the desired location where you want to create your project folder. You can use the cd command to change directories. For example:


Create a folder for your project. You can use the mkdir command followed by the name of your folder. For example:
Navigate into the project folder:
Initialize a Git repository using the git init command:

Commit your changes. This records the changes you've made to the repository:


Q.2) Create a separate environ\ent so that you do not \ess up with your base environ\entH. 

Install virtualenv: pip install virtualenv
Create a new environment: virtualenv my_project_env
Activate the environment:
Windows: my_project_env\Scripts\activate
macOS/Linux: source my_project_env/bin/activate
Now, proceed to create your project folder and initialize Git.

Q.3) Create the folder structure/directories and files using the python progra\\e re=uired for a ML projectI
You can refer the following project structure.

In [3]:
import os

def create_ml_project_structure(project_name):
    # Define project structure
    structure = {
        'data': ['raw', 'processed'],
        'models': [],
        'notebooks': [],
        'src': ['data_processing', 'model_training'],
        'reports': ['figures', 'logs']
    }


    os.mkdir(project_name)
    os.chdir(project_name)

    for folder, subfolders in structure.items():
        os.mkdir(folder)
        os.chdir(folder)
        for subfolder in subfolders:
            os.mkdir(subfolder)
        os.chdir('..')

    for folder in ['src/data_processing', 'src/model_training']:
        os.chdir(folder)
        open('__init__.py', 'a').close() 
        with open('{}.py'.format(folder.split('/')[-1]), 'w') as file:
            file.write('# Placeholder for {} module'.format(folder.split('/')[-1]))
        os.chdir('../..')

if __name__ == '__main__':
    project_name = input("Enter project name: ")
    create_ml_project_structure(project_name)
    print("Project structure created successfully.")


Enter project name: 2
Project structure created successfully.


Q.4) write the progra\ for setupIpy and the relevant dependencies in re=uire\entsItxt and generate
eggIinfo folder.

In [4]:
import os

def create_setup_files():
    # Create setup.py
    with open('setup.py', 'w') as setup_file:
        setup_file.write('''from setuptools import setup, find_packages

setup(
    name='your_project_name',
    version='0.1',
    packages=find_packages(),
    install_requires=[
        # List your dependencies here
        'numpy',
        'pandas',
        'scikit-learn',
    ],
)
''')

    # Create requirements.txt
    with open('requirements.txt', 'w') as requirements_file:
        requirements_file.write('''numpy
pandas
scikit-learn
''')

def generate_egg_info():
    os.system('python setup.py egg_info')

if __name__ == '__main__':
    create_setup_files()
    generate_egg_info()
    print("Setup files and egg-info folder generated successfully.")


Setup files and egg-info folder generated successfully.


Q.5) Write the logging function in loggerIpy and exception function in exceptionIpy file to be used for the
project to track the progress when the ML project is run and to raise any exception when encounteredI

from logger import setup_logging, log
from exceptions import CustomError
setup_logging()

try:
    # Your ML code here
    log("ML project started...")
    # Raise custom exception if needed
    raise CustomError("An error occurred during model training")
except CustomError as e:
    log(f"Custom error encountered: {e}", level=logging.ERROR)


Q.6) I'=t4e='ote8ook=-oler=create=a=jup*ter='ote8ook=i'sie=it=a'=o=t4e=-ollo#i';=
 Explorator*=Data='al*si&
 Feature=Engeering';i'eeri':
 Model=Trai'i':
 'Selection'=o-=8est=moel=usi';=metri,

Notebook Boilerplate: Create a Jupyter Notebook as the main interface for the project.

Initial Dataset Exploration: Start with exploratory data analysis (EDA) to understand the dataset's structure, statistics, and any patterns.

Feature Engineering: Process the raw data and extract relevant features to improve model performance.

Model Training: Train machine learning models using appropriate algorithms, techniques, and evaluation metrics.

Model Selection: Choose the best-performing model based on evaluation metrics and cross-validation.

Q.8) Write=a=separate=p*t4o'=pro;ram=i'=import_ata.p*=-ile=to=loa=t4e=me'tio'e=ataset=-rom=
sklear'.loa_ataset.loa_8reast_ca'cer=to=*our=Mo';

In [7]:
import pandas as pd
from sklearn.datasets import load_breast_cancer

def load_dataset_to_dataframe():
 
    data = load_breast_cancer()

   
    df = pd.DataFrame(data.data, columns=data.feature_names)

    df['target'] = data.target

    return df

if __name__ == "__main__":

    breast_cancer_df = load_dataset_to_dataframe()

 
    print(breast_cancer_df.head())


   mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0             

Q.9) In data_ingestion.py=write aprogram to load the same ataset rom=t4e=Mo';oD =to=*our=s*stem=i'=
DataFrame format.

In [8]:
import pandas as pd
from sklearn.datasets import load_iris

def load_dataset_to_dataframe():

    data = load_iris()

   
    df = pd.DataFrame(data.data, columns=data.feature_names)

   
    df['target'] = data.target

    return df

if __name__ == "__main__":
    iris_df = load_dataset_to_dataframe()

    print(iris_df.head())


   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  


Q.10) Do the necessary feature enginneering part in data_transformation.py.


In [9]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.datasets import load_iris

def load_dataset_to_dataframe():
    data = load_iris()

    df = pd.DataFrame(data.data, columns=data.feature_names)

    df['target'] = data.target

    return df

def preprocess_data(df):
    # Separate features and target
    X = df.drop('target', axis=1)
    y = df['target']

    
    numerical_features = X.columns


Q.11) Create the machine learning model_trainer.py ?

In [10]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.datasets import load_iris

def load_dataset_to_dataframe():
    # Load Iris dataset
    data = load_iris()

    # Convert to DataFrame
    df = pd.DataFrame(data.data, columns=data.feature_names)

    # Add target column to DataFrame
    df['target'] = data.target

    return df

def preprocess_data(df):
    # Separate features and target
    X = df.drop('target', axis=1)
    y = df['target']


    numerical_features = X.columns

    preprocessor = ColumnTransformer(
        transformers=[
            ('num', StandardScaler(), numerical_features)
        ],
        remainder='passthrough'
    )

    X_transformed = preprocessor.fit_transform(X)

    return X_transformed, y

if __name__ == "__main__":

    iris_df = load_dataset_to_dataframe()

    X_transformed, y = preprocess_data(iris_df)

    print("Preprocessed Features:")
    print(X_transformed)


Preprocessed Features:
[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45

12.) Use flask to deploy the project ?

Train Your Model: First, train your machine learning model using your dataset. Once the model is trained and you're satisfied with its performance, save it to a file. Common formats for saving models include pickle files (.pkl) or joblib files (.joblib).

Install Flask: Make sure you have Flask installed in your Python environment. You can install Flask using pip:

Create Flask App: Create a new Python file, typically named app.py, to define your Flask application. In this file, you'll define routes to handle incoming requests and make predictions using your trained model.

Load Your Model: In your Flask app, load your trained model from the saved file. You'll need to import the necessary libraries and load the model object.

Define Routes: Define routes in your Flask app to handle different types of requests. For example, you might have a route to accept POST requests containing data to make predictions.

Make Predictions: When a request is received, use the loaded model to make predictions on the input data. Return the predictions as a response to the client.

Run the Flask App: Run your Flask app using the flask run command. By default, Flask runs on http://127.0.0.1:5000/ locally.

Test Your API: Once your Flask app is running, you can test it by sending requests to the defined routes. You can use tools like cURL, Postman, or write a simple Python script to send requests and receive responses.

Deployment: When you're ready to deploy your Flask app, you can use various deployment options such as cloud platforms (e.g., Heroku, AWS, Google Cloud), Docker containers, or traditional web servers (e.g., Nginx, Apache).

Monitoring and Maintenance: After deployment, monitor your Flask app for any issues or performance bottlenecks. You may need to update your app with new features or improvements over time.